NotEnoughDiamond: "&aYou don not have enough diamonds so you can not send a super chat."
SuperChatSuccess: " &6Sent a super chat: "
PermissionMessage: "&4You do not have permission to do this."
InCoolDown: "&cCommand cooling down, remaining seconds: "
NotDiamond: "&cWhat you are holding is not a diamond."
NotPlayer: "&cOnly player can use this command."
CostAmount: 15
CoolDownTime: 20
